# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/meep_scattering_tutorial.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/meep_scattering_tutorial.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/meep_scattering_tutorial.ipynb 4
def foo(): pass
